### PR TITLE
Tutorial: Add a step to test out the new Ingress

### PR DESCRIPTION
**Pull request by G-Harmon**
This adds a step, after setting up the MCI, to try it out.
Also adds "-i" to the sed command, to make the change in-place.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/54)

### CODE REVIEW

**Comment by madhusudancs** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/zone-printer/README.md, line 189 at r1](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/54#-Ky2ZAzWa4kkTKMB4Jsy:-Ky2ZAzWa4kkTKMB4Jsz:bjihnm4) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/053eaf220a8563c87938656451d36521a91f697f/examples/zone-printer/README.md#L189)):*
> ```Markdown
> 
> ```shell
> ZP_KUBEMCI_IP="zp-kubemci-ip" gcloud compute addresses create \
> ```

While you are at it, can you also please fix this? I.e. break this out into 2 separate commands: one that sets the variable and the other that runs the gcloud command?

---

*[examples/zone-printer/README.md, line 199 at r1](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/54#-Ky2Yyt7fvQ2qkOipnBc:-Ky2Yyt87khFVEkgY9lP:b-ly26mh) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/053eaf220a8563c87938656451d36521a91f697f/examples/zone-printer/README.md#L199)):*
> ```Markdown
> 
> ```shell
> sed -i -e "s/\$ZP_KUBEMCI_IP/${ZP_KUBEMCI_IP}/" ingress/nginx.yaml
> ```

Oops. This was my fault, sorry. I was trying it out on my local machine and did not want to override the original files while testing. Thanks for fixing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/54)*

**Comment by G-Harmon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/zone-printer/README.md, line 189 at r1](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/54#-Ky2ZAzWa4kkTKMB4Jsy:-Ky32j7T_HeX_aej1keS:b-z7ntc4) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/053eaf220a8563c87938656451d36521a91f697f/examples/zone-printer/README.md#L189)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

While you are at it, can you also please fix this? I.e. break this out into 2 separate commands: one that sets the variable and the other that runs the gcloud command?
</blockquote></details>

Done. I don't think we need "export".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/54)*

**Comment by madhusudancs** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/zone-printer/README.md, line 189 at r1](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/54#-Ky2ZAzWa4kkTKMB4Jsy:-Ky4keY6qVlnrxySfNVr:bwfqyyu) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/053eaf220a8563c87938656451d36521a91f697f/examples/zone-printer/README.md#L189)):*
<details><summary><i>Previously, G-Harmon wrote…</i></summary><blockquote>

Done. I don't think we need "export".
</blockquote></details>

Thanks. Yeah, I don't think we need export.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/54#-:-Ky4kjGjOB0P_F7s_IjU:bnfp4nl)*

**Comment by madhusudancs** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/54)*

**Pull request merged**
