### PR TITLE
Fixing the coveralls missing repotoken problem

### PR DESCRIPTION
**Pull request by G-Harmon**
I mainly want to run the tests against this PR, and probably not check it in.

cc @nikhiljindal @BenTheElder

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/66)

### CODE REVIEW

**Comment by G-Harmon** [comment]
Okay, I think we figured out the problem (described in the commit msg now). PTAL.

**Comment by nikhiljindal** [comment]
/lgtm
Will merge once tests pass

**Comment by G-Harmon** [comment]
okay, looks like coveralls succeeded! (https://coveralls.io/builds/14221758)
Unfortunately, I haven't seen Coveralls post coverage data back to this PR.
anyway, I think this is ready to merge.

**Pull request merged**
