### PR TITLE
Update GCE cluster version in the README.md

### PR DESCRIPTION
**Pull request by kuanghaochina**
Update cluster version to latest "1.8.4.gke-1" since "1.8.0-gke.0" has been removed from the list.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
/ok-to-test

Thanks for the update.
Why not use the same cluster version everywhere? I see that you are using a different one for europe-west1-c

**Comment by kuanghaochina** [comment]
@nikhiljindal I would like to but I don't know why europe-west1-c doesn't have version 1.8.4.gke-0 and some of the zones under europe does and some of them doesn't. May be europe-west1-c could be updated to europe-west2-c which has 1.8.4.gke-0 instead of 1.8.4.gke-1.

**Comment by nikhiljindal** [comment]
Thanks @kuanghaochina 
I would say that these version numbers are for illustrative purposes only.
There is no way we can keep them updated all the time.

Just choose any one version and use it in all zones.

**Comment by kuanghaochina** [comment]
@nikhiljindal Thanks for the response.  It makes sense. We can close it.

**Comment by madhusudancs** [comment]
@nikhiljindal @kuanghaochina 

I would say update it to a version that's available now (`1.8.4-gke.0` in this PR is correct) until the minimum required version (`1.8.x+`) becomes the default. When `1.8.x+` becomes the default, just remove `--cluster-version` altogether from the examples.

In short, I would suggest merging this PR.

**Comment by nikhiljindal** [comment]
Yes, am fine merging this PR but I will prefer selecting a version that works in all zones.

**Comment by G-Harmon** [comment]
I checked the available versions again today (1/4/18), and now these 3 zones all have 1.8.4-gke.1. You were probably seeing things in the middle of its rollout.

**Comment by kuanghaochina** [comment]
@G-Harmon I think so and I just updated them to the latest version. Thanks for the check.

**Comment by nikhiljindal** [comment]
aah didnt realize that this had 3 commits.
@kuanghaochina for next time, we request squashing commits before merging.

**Comment by kuanghaochina** [comment]
@nikhiljindal em. forgot to squash and will pay attention next time. Thanks.

**Pull request merged**
