### PR TITLE
Adding more unit tests for remove-clusters

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/58 and https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/145

Fixing TODOs from https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/151 and https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/149

Adding more unit tests for remove-clusters command.
Bulk of the PR is unit test changes, with minor bug fixes.

cc @csbell @G-Harmon @madhusudancs @perotinus

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/kubemci/pkg/gcp/backendservice/fake_backendservicesyncer.go, line 85 at r1](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8n1O6-9EOIzGkZxUKj:-L8oNNsH5TgJPdPwb4wj:bss9o7z) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/b4dbf7acc97e6c2e38d1b65d1ef0943a7a3fc484/app/kubemci/pkg/gcp/backendservice/fake_backendservicesyncer.go#L85)):*
<details><summary><i>Previously, G-Harmon wrote…</i></summary><blockquote>

Can v.IGLinks have duplicates? If not, then this code doesn't look like it does anything.
</blockquote></details>

Yes our tests have duplicates. Added a comment to make that explicit

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, line 361 at r1](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8n0eBgDkozPw7ykRn6:-L8oNRIr2hvtbyDGO2Ib:b-p8sgcb) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/b4dbf7acc97e6c2e38d1b65d1ef0943a7a3fc484/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go#L361)):*
<details><summary><i>Previously, G-Harmon wrote…</i></summary><blockquote>

>  sd != nil
why the check here?
Overall, this logic seems complex/fragile. partially, I don't quite follow what you're doing here.
</blockquote></details>

Updated the variable names to clarify this as discussed. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158)*

**Comment by nikhiljindal** [comment]
Thanks for the review @G-Harmon 
Updated as per comments. PTAL

**Comment by G-Harmon** [comment]
I didn't quite follow the changes in loadbalancersyncer_test.go. I put questions there in that part of the patch.

---

Reviewed 3 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, line 352 at r2](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8sfYOk-JSzs3REzoDJ:-L8sfYOk-JSzs3REzoDK:b-ynyi5y) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/6d3e40ed68e7e142188b0b6aa9e82bb41773e231/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go#L352)):*
>Sd
Why is this called sd? It returns a LoadBalancerStatus...

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, line 369 at r2](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8sidP88a6x4PV9BXp9:-L8sidP88a6x4PV9BXpA:b60oami) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/4b9401319604b4c92353930eab1928de7d9fae87/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go#L369)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	fhc := lbc.hcs.(*healthcheck.FakeHealthCheckSyncer)
> 	if len(fhc.EnsuredHealthChecks) == 0 {
> 		t.Errorf("unexpected health checks not created")
> 	}
> ```
</details>

Why do you remove some checks? like health checks, url maps, target proxies, forwarding rules?

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, line 426 at r2](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8siqEs0kE4u9B2tKw1:-L8siqEs0kE4u9B2tKw2:bve8nos) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/6d3e40ed68e7e142188b0b6aa9e82bb41773e231/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go#L426)):*
> ```
> 	if !reflect.DeepEqual(fw.IGLinks, expectedFWIGLinks) {
> 		t.Errorf("unexpected IG links on firewall rule, expected: %v, got: %v", expectedFWIGLinks, fw.IGLinks)
> 	}
> ```
(Why don't you check as many things as before? like forwarding rules)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-:-L8sjP88-LQ4jqaXe770:b93fgwj)*

**Comment by nikhiljindal** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, line 352 at r2](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8sfYOk-JSzs3REzoDJ:-L8t1SMD1-9pFDwHD4dS:bc15wij) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/6d3e40ed68e7e142188b0b6aa9e82bb41773e231/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go#L352)):*
<details><summary><i>Previously, G-Harmon wrote…</i></summary><blockquote>

>Sd
Why is this called sd? It returns a LoadBalancerStatus...

</blockquote></details>

sd for status description :)
Renamed to status.

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, line 369 at r2](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8sidP88a6x4PV9BXp9:-L8t2S5N28rIF_gTC-1O:bczodtq) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/4b9401319604b4c92353930eab1928de7d9fae87/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go#L369)):*
<details><summary><i>Previously, G-Harmon wrote…</i></summary><blockquote>

> ```
> 	fhc := lbc.hcs.(*healthcheck.FakeHealthCheckSyncer)
> 	if len(fhc.EnsuredHealthChecks) == 0 {
> 		t.Errorf("unexpected health checks not created")
> 	}
> ```
Why do you remove some checks? like health checks, url maps, target proxies, forwarding rules?
</blockquote></details>

They are not affected by RemoveFromClusters.
Those were essentially testing that CreateLoadBalancer is working as expected, which is duplicated in the relevant test already.

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, line 426 at r2](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8siqEs0kE4u9B2tKw1:-L8t2fq67NcgWXrEoCsD:bb489q) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/6d3e40ed68e7e142188b0b6aa9e82bb41773e231/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go#L426)):*
<details><summary><i>Previously, G-Harmon wrote…</i></summary><blockquote>

> ```
> 	if !reflect.DeepEqual(fw.IGLinks, expectedFWIGLinks) {
> 		t.Errorf("unexpected IG links on firewall rule, expected: %v, got: %v", expectedFWIGLinks, fw.IGLinks)
> 	}
> ```
(Why don't you check as many things as before? like forwarding rules)
</blockquote></details>

Same as above. Here am limiting the checks to resources that are affected by RemoveFromClusters.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158)*

**Comment by nikhiljindal** [comment]
Updated code as per comments.
@G-Harmon PTAL

**Comment by G-Harmon** [comment]
:lgtm:
Feel free to merge as is, or add the one more tiny check.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, line 369 at r2](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8sidP88a6x4PV9BXp9:-L8zLpCPCJULKh6Y_bcG:b-skxs6b) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/4b9401319604b4c92353930eab1928de7d9fae87/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go#L369)):*
<details><summary><i>Previously, nikhiljindal (Nikhil Jindal) wrote…</i></summary><blockquote>

They are not affected by RemoveFromClusters.
Those were essentially testing that CreateLoadBalancer is working as expected, which is duplicated in the relevant test already.
</blockquote></details>

ah, okay, sounds good.

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, line 452 at r3](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8zL5Oq0ygarchOR5kF:-L8zL5Oq0ygarchOR5kG:brg16f9) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/17d2ddfd8d7124bb73cb0966d57c6b73707d36b0/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go#L452)):*
> ```
> be := fbs.EnsuredBackendServices[0]
> ```
Do we care about verifying both? I think I submitted this shortcoming, so totally optional.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-:-L8zLmx46dcQ7YjE27Uf:b-qukomq)*

**Comment by nikhiljindal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, line 452 at r3](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8zL5Oq0ygarchOR5kF:-L93Lxyy8BOJZanEK55C:b-9x6g09) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/17d2ddfd8d7124bb73cb0966d57c6b73707d36b0/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go#L452)):*
<details><summary><i>Previously, G-Harmon wrote…</i></summary><blockquote>

> ```
> be := fbs.EnsuredBackendServices[0]
> ```
Do we care about verifying both? I think I submitted this shortcoming, so totally optional.
</blockquote></details>

Good catch. Updated to verify both

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158)*

**Comment by nikhiljindal** [comment]
Thanks for the review @G-Harmon 
Updated code as per comments.

Will merge once tests pass.

**Comment by G-Harmon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, line 452 at r3](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-L8zL5Oq0ygarchOR5kF:-L963QA_4QYYMB5oEyrb:bd5l6mr) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/17d2ddfd8d7124bb73cb0966d57c6b73707d36b0/app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go#L452)):*
<details><summary><i>Previously, nikhiljindal (Nikhil Jindal) wrote…</i></summary><blockquote>

Good catch. Updated to verify both
</blockquote></details>

thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158#-:-L963SnSByBMmcw8BUQl:bnfp4nl)*

**Pull request merged**
