### PR TITLE
Add Coverage widget to Readme.

### PR DESCRIPTION
**Pull request by G-Harmon**
cc @nikhiljindal @csbell @madhusudancs

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/64)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
/ok-to-test

This is awesome, @G-Harmon love it!

**Comment by nikhiljindal** [comment]
From the logs:
```
I1114 21:34:33.940] Call:  /workspace/./test-infra/jenkins/../scenarios/execute.py make -j 2 test coveralls
W1114 21:34:33.963] usage: execute.py [-h] [--env ENV] cmd [args [args ...]]
W1114 21:34:33.963] execute.py: error: unrecognized arguments: -j 2 test coveralls
E1114 21:34:33.964] Command failed
```
cc @G-Harmon @BenTheElder xref https://github.com/kubernetes/test-infra/pull/5462

**Comment by BenTheElder** [comment]
Agh,  @krzyzacy why is execute scenario parsing args? :(

**Comment by krzyzacy** [comment]
oh, do `make -- -j foo bar`

**Pull request merged**
