### PR TITLE
Updating the code to use kubemci instead of mci

### PR DESCRIPTION
**Pull request by nikhiljindal**
Updating the code to use kubemci instead of mci.
This involves using kubemci in command description strings and updating the code directory and files to be named kubemci instead of mci.
Note that the prefix for GCP resources is still "mci1".

cc @G-Harmon @csbell @madhusudancs

### CODE REVIEW

**Comment by nikhiljindal** [comment]
The first commit is from https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/14 and hence should be ignored while reviewing this PR.

**Comment by G-Harmon** [comment]
LGTM
Can you commit description to be a little clearer that this is "renaming the tool kubemci" or something?

**Comment by nikhiljindal** [comment]
Rebased and updated the commit message.
Thanks for the review @G-Harmon

**Pull request merged**
