### PR TITLE
Adding more information to README

### PR DESCRIPTION
**Pull request by nikhiljindal**
Adding information on how to get started and how to contribute.
Also added links to the example, FAQs doc, contributing doc and the video demo.

cc @G-Harmon

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/67)

### CODE REVIEW

**Comment by G-Harmon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 26 at r1](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/67#-Kz5ow5owjsjXyT96XjM:-Kz5ow5p4zCcas0SJRfx:b-fcywj0) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/c2b54b38ea0869e425ed0b2f9f4b0d6e6bdf94cb/README.md#L26)):*
> ```Markdown
> ## Contributing
> 
> See [CONTRIBUTING.md](/CONTRIBUTING.md) for instructions on how to contribute.
> ```

I see the CONTRIBUTING.md page has a mal-formed link: This shows up in literal text: (glide)[https://github.com/Masterminds/glide] 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/67)*

**Comment by nikhiljindal** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 26 at r1](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/67#-Kz5ow5owjsjXyT96XjM:-Kz5xSqysJUi9oR1xW7L:bok1p6t) ([raw file](https://github.com/googlecloudplatform/k8s-multicluster-ingress/blob/c2b54b38ea0869e425ed0b2f9f4b0d6e6bdf94cb/README.md#L26)):*
<details><summary><i>Previously, G-Harmon wrote…</i></summary><blockquote>

I see the CONTRIBUTING.md page has a mal-formed link: This shows up in literal text: (glide)[https://github.com/Masterminds/glide] 
</blockquote></details>

Good catch. Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/67)*

**Comment by nikhiljindal** [comment]
Thanks Greg. Updated code as per comments

**Comment by G-Harmon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/googlecloudplatform/k8s-multicluster-ingress/67#-:-Kz63u9CJTbtU6AYcksp:bnfp4nl)*

**Pull request merged**
